const ActionTypes = {
    // GET_USER: 'GET_USER',
    GET_USERS: 'GET_USERS',
    GET_USERS_SUCCEED: 'GET_USERS_SUCCEED',
    GET_USERS_FAILED: 'GET_USERS_FAILED',

    ADD_USER: 'ADD_USER',
    ADD_USER_SUCCEED: 'ADD_USER_SUCCEED',
    ADD_USER_FAILED: 'ADD_USER_FAILED',

    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCEED: 'UPDATE_USER_SUCCEED',
    UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',
    
    DEL_USER: 'DEL_USER',
    DEL_USER_SUCCEED: 'DEL_USER_SUCCEED',
    DEL_USER_FAILED: 'DEL_USER_FAILED',


};

export default ActionTypes;